# Global

hystrix_version: 0.1

hystrix_archive_name: 'hystrix-{{ hystrix_version }}.zip'

hystrix_archive_url: 'https://github.com/micro-platform/hystrix/releases/download/{{ hystrix_version }}/{{ hystrix_archive_name }}'

hystrix_temp_destination: ../tmp/hystrix

# Docker

hystrix_docker_image_name: '{{ docker_prefix }}/hystrix'
hystrix_docker_container_name: hystrix
hystrix_docker_container_port: 8989