---


  - name : Copy pip requirements file
    copy:
      src: '{{ role_path }}/files/requirements.txt'
      dest: '{{ requirements_dest }}'

  - name: Ensure docker-* tooling  is present
    pip:
      executable: pip
      requirements: '{{ requirements_dest }}'
      state: present

  - name: Ensure docker service is running
    service:
      name: docker
      state: started